config/routes.rb
Candyscup::Application.routes.draw do
  get "page/home"

  get "user_sessions/new"

  resources :team_player_days

  resources :teams

  resources :users

  resources :player_days

  resources :days

  resources :players

  resources :leagues

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  root :to => 'page#home'

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :league
  attr_accessible :day, :number
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  # GET /days
  # GET /days.json
  def index
    @days = Day.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @days }
    end
  end

  # GET /days/1
  # GET /days/1.json
  def show
    @day = Day.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @day }
    end
  end

  # GET /days/new
  # GET /days/new.json
  def new
    @day = Day.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @day }
    end
  end

  # GET /days/1/edit
  def edit
    @day = Day.find(params[:id])
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(params[:day])

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render json: @day, status: :created, location: @day }
      else
        format.html { render action: "new" }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /days/1
  # PUT /days/1.json
  def update
    @day = Day.find(params[:id])

    respond_to do |format|
      if @day.update_attributes(params[:day])
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day = Day.find(params[:id])
    @day.destroy

    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :league %><br />
    <%= f.text_field :league %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Day</th>
    <th>League</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @days.each do |day| %>
  <tr>
    <td><%= day.number %></td>
    <td><%= day.day %></td>
    <td><%= day.league %></td>
    <td><%= link_to 'Show', day %></td>
    <td><%= link_to 'Edit', edit_day_path(day) %></td>
    <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @day.number %>
</p>

<p>
  <b>Day:</b>
  <%= @day.day %>
</p>

<p>
  <b>League:</b>
  <%= @day.league %>
</p>


<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>