config/routes.rb
Candyscup::Application.routes.draw do
  get "page/home"

  get "user_sessions/new"

  resources :team_player_days

  resources :teams

  resources :users

  resources :player_days

  resources :days

  resources :players

  resources :leagues

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  root :to => 'page#home'

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :league
  attr_accessible :club, :name, :role, :league_id
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="center">

	<%= form_for(@player) do |f| %>
	  <% if @player.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>
	
	      <ul>
	      <% @player.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= f.label :name %><br />
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :role %><br />
	    <%= f.text_field :role %>
	  </div>
	  <div class="field">
	    <%= f.label :club %><br />
	    <%= f.text_field :club %>
	  </div>
	  <div class="field">
	    <%= f.label :league %><br />
	    <%= collection_select(:player, :league_id, League.all, :id, :name) %>
	  </div>
	  <div class="actions">
	    <%= f.submit "Done", :class => 'btn' %>
	  </div>
	<% end %>
</div>

app/views/players/edit.html.erb
<%= title :title => "Player" %>
<div class="center description">
Please choose TODO
</div>
<%= render 'form' %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Role</th>
    <th>Club</th>
    <th>League</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.role %></td>
    <td><%= player.club %></td>
    <td><%= player.league %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<p>
  <b>Role:</b>
  <%= @player.role %>
</p>

<p>
  <b>Club:</b>
  <%= @player.club %>
</p>

<p>
  <b>League:</b>
  <%= @player.league %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>