config/routes.rb
Candyscup::Application.routes.draw do
  get "page/home"

  get "user_sessions/new"

  resources :team_player_days

  resources :teams

  resources :users

  resources :player_days

  resources :days

  resources :players

  resources :leagues

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  root :to => 'page#home'

end

app/models/player_day.rb
class PlayerDay < ActiveRecord::Base
  belongs_to :player
  belongs_to :day
  attr_accessible :goals, :redcards, :vote, :yellowcards
end

app/controllers/player_days_controller.rb
class PlayerDaysController < ApplicationController
  # GET /player_days
  # GET /player_days.json
  def index
    @player_days = PlayerDay.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @player_days }
    end
  end

  # GET /player_days/1
  # GET /player_days/1.json
  def show
    @player_day = PlayerDay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player_day }
    end
  end

  # GET /player_days/new
  # GET /player_days/new.json
  def new
    @player_day = PlayerDay.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player_day }
    end
  end

  # GET /player_days/1/edit
  def edit
    @player_day = PlayerDay.find(params[:id])
  end

  # POST /player_days
  # POST /player_days.json
  def create
    @player_day = PlayerDay.new(params[:player_day])

    respond_to do |format|
      if @player_day.save
        format.html { redirect_to @player_day, notice: 'Player day was successfully created.' }
        format.json { render json: @player_day, status: :created, location: @player_day }
      else
        format.html { render action: "new" }
        format.json { render json: @player_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /player_days/1
  # PUT /player_days/1.json
  def update
    @player_day = PlayerDay.find(params[:id])

    respond_to do |format|
      if @player_day.update_attributes(params[:player_day])
        format.html { redirect_to @player_day, notice: 'Player day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_days/1
  # DELETE /player_days/1.json
  def destroy
    @player_day = PlayerDay.find(params[:id])
    @player_day.destroy

    respond_to do |format|
      format.html { redirect_to player_days_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/player_days_helper.rb
module PlayerDaysHelper
end

app/views/player_days/_form.html.erb
<%= form_for(@player_day) do |f| %>
  <% if @player_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_day.errors.count, "error") %> prohibited this player_day from being saved:</h2>

      <ul>
      <% @player_day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player %><br />
    <%= f.text_field :player %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :vote %><br />
    <%= f.text_field :vote %>
  </div>
  <div class="field">
    <%= f.label :goals %><br />
    <%= f.number_field :goals %>
  </div>
  <div class="field">
    <%= f.label :yellowcards %><br />
    <%= f.number_field :yellowcards %>
  </div>
  <div class="field">
    <%= f.label :redcards %><br />
    <%= f.number_field :redcards %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_days/edit.html.erb
<h1>Editing player_day</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_day %> |
<%= link_to 'Back', player_days_path %>

app/views/player_days/index.html.erb
<h1>Listing player_days</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Day</th>
    <th>Vote</th>
    <th>Goals</th>
    <th>Yellowcards</th>
    <th>Redcards</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @player_days.each do |player_day| %>
  <tr>
    <td><%= player_day.player %></td>
    <td><%= player_day.day %></td>
    <td><%= player_day.vote %></td>
    <td><%= player_day.goals %></td>
    <td><%= player_day.yellowcards %></td>
    <td><%= player_day.redcards %></td>
    <td><%= link_to 'Show', player_day %></td>
    <td><%= link_to 'Edit', edit_player_day_path(player_day) %></td>
    <td><%= link_to 'Destroy', player_day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player day', new_player_day_path %>

app/views/player_days/new.html.erb
<h1>New player_day</h1>

<%= render 'form' %>

<%= link_to 'Back', player_days_path %>

app/views/player_days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Player:</b>
  <%= @player_day.player %>
</p>

<p>
  <b>Day:</b>
  <%= @player_day.day %>
</p>

<p>
  <b>Vote:</b>
  <%= @player_day.vote %>
</p>

<p>
  <b>Goals:</b>
  <%= @player_day.goals %>
</p>

<p>
  <b>Yellowcards:</b>
  <%= @player_day.yellowcards %>
</p>

<p>
  <b>Redcards:</b>
  <%= @player_day.redcards %>
</p>


<%= link_to 'Edit', edit_player_day_path(@player_day) %> |
<%= link_to 'Back', player_days_path %>